### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-turisteando-por-mexico#1]
[ROADMAP (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-turisteando-por-mexico/files/13443865/ROADMAP.1.pdf)

**Comment by josealfredo79** [comment]
Faltan los costos

**Comment by josealfredo79** [comment]
Para que se pueda tomar en cuenta la tarea por favor

**Comment by NoeliaGlez** [comment]
ya fue editado el documento ing

**Comment by JudithReynaCS** [comment]
Calificacion:30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
