### ISSUE TITLE
Contrato

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-turisteando-por-mexico#2]
[Contrato_Turisteando.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-turisteando-por-mexico/files/13620607/Contrato_Turisteando.pdf)

**Comment by josealfredo79** [comment]
Calificacion 50
